version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - set -e
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync "./public/" s3://$S3_BUCKET --delete --acl public-read
      - aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DIST_ID --paths "/*"
